USE [master]
GO

/****** Object:  Database [CrudAndressa]    Script Date: 14/02/2022 10:46:14 ******/
CREATE DATABASE [CrudAndressa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CrudAndressa', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CrudAndressa.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CrudAndressa_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CrudAndressa_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CrudAndressa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CrudAndressa] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CrudAndressa] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CrudAndressa] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CrudAndressa] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CrudAndressa] SET ARITHABORT OFF 
GO

ALTER DATABASE [CrudAndressa] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CrudAndressa] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CrudAndressa] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CrudAndressa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CrudAndressa] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CrudAndressa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CrudAndressa] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CrudAndressa] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CrudAndressa] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CrudAndressa] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CrudAndressa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CrudAndressa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CrudAndressa] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CrudAndressa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CrudAndressa] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CrudAndressa] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CrudAndressa] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CrudAndressa] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CrudAndressa] SET  MULTI_USER 
GO

ALTER DATABASE [CrudAndressa] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CrudAndressa] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CrudAndressa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CrudAndressa] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CrudAndressa] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CrudAndressa] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CrudAndressa] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CrudAndressa] SET  READ_WRITE 
GO

